[package]
name = "rust_struct_crusher_240418"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc="*"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tqdm = "0.6"
tree-sitter = "0.22"
tree-sitter-rust = "0.21"
walkdir = "2"
